name: Sync With Hugging Face Hub
description: Sync a GitHub repository to the Hugging Face Hub using the hf CLI
author: alozowski
branding:
  icon: upload-cloud
  color: yellow

inputs:
  github_repo_id:
    required: true
    type: string
  subdirectory:
    type: string
    default: ''
  huggingface_repo_id:
    required: true
    type: string
  hf_token:
    required: true
  repo_type:
    type: string
    default: 'space'
  space_sdk:
    type: string
    default: 'gradio'
  private:
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v5

    - name: Create Hugging Face repo (idempotent)
      shell: bash
      run: |
        set -euo pipefail

        CREATE_ARGS=(
          hf repo create "${{ inputs.huggingface_repo_id }}"
          --repo-type "${{ inputs.repo_type }}"
          --token "${{ inputs.hf_token }}"
          --exist-ok
        )

        if [[ "${{ inputs.private }}" == "true" ]]; then
          CREATE_ARGS+=(--private)
        fi

        if [[ "${{ inputs.repo_type }}" == "space" ]]; then
          CREATE_ARGS+=(--space-sdk "${{ inputs.space_sdk }}")
        fi

        uvx "${CREATE_ARGS[@]}"

    - name: Upload files to Hugging Face (mirror)
      shell: bash
      run: |
        set -euo pipefail

        SRC_DIR="."
        if [[ -n "${{ inputs.subdirectory }}" ]]; then
          SRC_DIR="${{ inputs.subdirectory }}"
        fi

        uvx hf upload \
          "${{ inputs.huggingface_repo_id }}" \
          "${SRC_DIR}" \
          --repo-type "${{ inputs.repo_type }}" \
          --token "${{ inputs.hf_token }}" \
          --delete="*"
