name: Sync With Hugging Face Hub
description: Sync a GitHub repository to the Hugging Face Hub using the hf CLI
author: alozowski
branding:
  icon: upload-cloud
  color: yellow

inputs:
  github_repo_id:
    required: true
    description: 'GitHub repository ID (owner/repo)'
  subdirectory:
    required: false
    description: 'Subdirectory to sync (optional, defaults to root)'
    default: ''
  huggingface_repo_id:
    required: true
    description: 'Hugging Face repository ID (owner/repo)'
  hf_token:
    required: true
    description: 'Hugging Face API token'
  repo_type:
    required: false
    description: 'Repository type (model, dataset, or space)'
    default: 'space'
  space_sdk:
    required: false
    description: 'Space SDK (gradio, streamlit, docker, or static) - only used when repo_type is space'
    default: 'gradio'
  private:
    required: false
    description: 'Whether the repository should be private'
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Sync to Hugging Face
      shell: bash
      env:
        HF_REPO_ID: ${{ inputs.huggingface_repo_id }}
        HF_TOKEN: ${{ inputs.hf_token }}
        REPO_TYPE: ${{ inputs.repo_type }}
        PRIVATE: ${{ inputs.private }}
        SPACE_SDK: ${{ inputs.space_sdk }}
        SUBDIRECTORY: ${{ inputs.subdirectory }}
      run: |
        set -euo pipefail
        
        echo "::group::Syncing GitHub repo to Hugging Face"
        echo "Repo ID: ${HF_REPO_ID}"
        echo "Repo type: ${REPO_TYPE}"
        echo "Private: ${PRIVATE}"
        if [[ "${REPO_TYPE}" == "space" ]]; then
          echo "Space SDK: ${SPACE_SDK}"
        fi
        if [[ -n "${SUBDIRECTORY}" ]]; then
          echo "Subdirectory: ${SUBDIRECTORY}"
        fi
        echo "::endgroup::"
        
        # Build create command
        echo "::group::Creating or updating Hugging Face repo"
        CREATE_CMD="uvx --from huggingface_hub hf repo create \"${HF_REPO_ID}\" --repo-type \"${REPO_TYPE}\" --exist-ok"
        
        if [[ "${PRIVATE}" == "true" ]]; then
          CREATE_CMD="${CREATE_CMD} --private"
        fi
        
        if [[ "${REPO_TYPE}" == "space" ]]; then
          CREATE_CMD="${CREATE_CMD} --space-sdk \"${SPACE_SDK}\""
        fi
        
        # Note: We don't pass the token via command line to avoid it appearing in logs
        # Instead, we'll use HF_TOKEN environment variable which huggingface_hub respects
        eval "${CREATE_CMD}"
        echo "::endgroup::"
        
        # Stage files into a clean directory before upload
        STAGING_DIR="$(mktemp -d)"
        trap 'rm -rf "${STAGING_DIR}"' EXIT
        
        echo "::group::Staging files"
        echo "Staging directory: ${STAGING_DIR}"
        
        # Determine source directory
        SRC_DIR="."
        if [[ -n "${SUBDIRECTORY}" ]]; then
          if [[ ! -d "${SUBDIRECTORY}" ]]; then
            echo "::error::Subdirectory '${SUBDIRECTORY}' does not exist"
            exit 1
          fi
          SRC_DIR="${SUBDIRECTORY}"
          echo "Using subdirectory: ${SRC_DIR}"
        fi
        
        # Save current directory and change to source
        ORIGINAL_DIR="$(pwd)"
        cd "${SRC_DIR}"
        
        # Check if we're in a git repository
        if ! git rev-parse --git-dir > /dev/null 2>&1; then
          echo "::error::Not in a git repository. This action requires the repository to be checked out with git."
          exit 1
        fi
        
        # Copy only tracked git files to avoid GitHub Actions artifacts
        echo "Copying tracked git files..."
        git ls-files -z | rsync -a --files-from=- --from0 ./ "${STAGING_DIR}/"
        
        # Return to original directory
        cd "${ORIGINAL_DIR}"
        
        # Count files staged
        FILE_COUNT=$(find "${STAGING_DIR}" -type f | wc -l)
        echo "Staged ${FILE_COUNT} files"
        
        # Safety check: fail fast if staging leaked infra
        if [[ -d "${STAGING_DIR}/.github" ]]; then
          echo "::error::.github directory leaked into staging area"
          exit 1
        fi
        
        # Additional safety checks
        if [[ -f "${STAGING_DIR}/.git" ]] || [[ -d "${STAGING_DIR}/.git" ]]; then
          echo "::error::.git directory leaked into staging area"
          exit 1
        fi
        
        if [[ ${FILE_COUNT} -eq 0 ]]; then
          echo "::error::No files to upload. Check that your repository has tracked files."
          exit 1
        fi
        
        echo "::endgroup::"
        
        # Upload staged contents (true mirror)
        echo "::group::Uploading to Hugging Face"
        echo "Uploading ${FILE_COUNT} files..."
        uvx --from huggingface_hub hf upload \
          "${HF_REPO_ID}" \
          "${STAGING_DIR}" \
          --repo-type "${REPO_TYPE}" \
          --delete="*" \
          --quiet
        echo "::endgroup::"
        
        echo "Sync completed successfully"
        echo "View at: https://huggingface.co/${HF_REPO_ID}"
